### PR TITLE
fix: Fixes toBufferBlock error when jsonBlock is null. Add getBlockByNumberWithRetry

### LINKED ISSUE #3130: Bug in @trufflesuite/web3-provider-engine 14.0.6 (dependency of @truffle/hdwallet-provider 1.0.36 where getBlockByNumber function of the blockTracker event listener sometimes returns a null block object and crashes applications with error `TypeError: Cannot read property 'number' of null`
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Truffle's fork of the Metamask web3-provider-engine doesn't include changes such as adding a `_getBlockByNumberWithRetry` and catering for when the block tracker event listener occasionally returns a block object that has a `null` value. As a result, when you use the dependency "@truffle/hdwallet-provider": "^1.0.36" (which depends on "@trufflesuite/web3-provider-engine" "14.0.6") in your project, it will eventually crash.

## Steps to Reproduce

It requires patience to reproduce because you have to wait until `_getBlockByNumber` eventually returns a `null` value, which could take over an hour.

To reproduce, clone my faucet project https://github.com/DataHighway-DHX/faucet, set it up by following the instructions in the README, which include installing Node.js 14.4.0 and Yarn.

Then modify the dependencies to add some console.logs for debugging by editing DataHighway-DHX/faucet-mining/node_modules/@trufflesuite/web3-provider-engine/index.js, and modifying the code by adding the section shown below between `// MODIFICATIONS START HERE` and `// MODIFICATIONS END HERE`:
```
  self._blockTracker.on('latest', (blockNumber) => {
    // get block body
    self._getBlockByNumber(blockNumber, (err, block) => {
      if (err) {
        this.emit('error', err)
        return
      }
      // MODIFICATIONS START HERE
      if (!block) {
        console.error('NO BLOCK: ', typeof block);
      }
      console.log('BLOCK: ', block);
      // MODIFICATIONS END HERE
      const bufferBlock = toBufferBlock(block)
```
Then run the code:
```
yarn global add nodemon;
DEBUG=app yarn dev;
```
And watch the terminal logs until the output becomes
```
[0] BLOCK: {
[0]   difficulty: '0x9bdeaf63',
[0]   extraData: '0x74657374',
[0]   gasLimit: '0x7a121d',
[0]   gasUsed: '0x20c1c',
[0]   hash: '0x593679a19b9cc02e52d819d9256d2c5e9a131cdecda98ef7dac144b240397720',
[0]   logsBloom: '0x00000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000',
[0]   miner: '0xbbf5029fd710d227630c8b7d338051b8e76d50b3',
[0]   mixHash: '0x97232baa933ebee13b4e14447ea8114bb8fc5652ee5dfc35caca3a4afb0f4ebd',
[0]   nonce: '0x0c736d40080dda7b',
[0]   number: '0x7d02c5',
[0]   parentHash: '0xbfc6dfaed1488da8edd72b18e9f770c0911b3a9f5edce5294e306a474824eb97',
[0]   receiptsRoot: '0xf279f211e14db07e36961789f6ba968f94b7b2413b3df218ca98effeeaab29a2',
[0]   sha3Uncles: '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347',
[0]   size: '0x36b',
[0]   stateRoot: '0x042ad505ab14e8dfb0bcba694418ea1b1a535ae4cbab3d04e69f0226e7bef091',
[0]   timestamp: '0x5ef9cb84',
[0]   totalDifficulty: '0x6cdaa9a19c28f4',
[0]   transactions: [
[0]     '0x86a58956c34fe668f0a9b3031b424939eb014112e351f7bd09140e62ab667ddf',
[0]     '0x8d37315790bf1ec21a27bf2acbac464035d18ec838e768235dd588d40956622b'
[0]   ],
[0]   transactionsRoot: '0x3bc040f4ab29394a3000efb4f88b6d6933b760d3da7e0bcd08d90b7b81ddf510',
[0]   uncles: []
[0] }
[0] NO BLOCK: object
[0] BLOCK: null
[0] 
[0] /Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/@trufflesuite/web3-provider-engine/index.js:223
[0]     number:           ethUtil.toBuffer(jsonBlock.number),
[0]                                                  ^
[0] TypeError: Cannot read property 'number' of null
[0]     at toBufferBlock (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/@trufflesuite/web3-provider-engine/index.js:223:50)
[0]     at /Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/@trufflesuite/web3-provider-engine/index.js:64:27
[0]     at /Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/@trufflesuite/web3-provider-engine/index.js:140:12
[0]     at /Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/@trufflesuite/web3-provider-engine/index.js:203:9
[0]     at /Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/async/internal/once.js:12:16
[0]     at replenish (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/async/internal/eachOfLimit.js:61:25)
[0]     at /Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/async/internal/eachOfLimit.js:71:9
[0]     at eachLimit (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/async/eachLimit.js:43:36)
[0]     at /Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/async/internal/doLimit.js:9:16
[0]     at end (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/@trufflesuite/web3-provider-engine/index.js:180:5)
[0]     at /Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/@trufflesuite/web3-provider-engine/subproviders/provider.js:19:5
[0]     at XMLHttpRequest.request.onreadystatechange (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/web3-providers-http/src/index.js:96:13)
[0]     at XMLHttpRequestEventTarget.dispatchEvent (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
[0]     at XMLHttpRequest._setReadyState (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
[0]     at XMLHttpRequest._onHttpResponseEnd (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
[0]     at IncomingMessage.<anonymous> (/Users/ls/code/src/DataHighway-com/faucet-mining/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
[0] [nodemon] app crashed - waiting for file changes before starting...
```

Then you've got evidence of where and why it crashed.

## Expected Behavior

I expected it not to crash. But now that I know that it crashes because the block object sometimes returns a `null` object, I know that to fix it we just need to make the same changes that MetaMask's web3-provider-engine did. They previously fixed that bug by exiting early from that getBlockByNumber function here https://github.com/MetaMask/web3-provider-engine/blob/master/index.js#L57, and more recently they just replaced the _getBlockByNumber function with a _getBlockByNumberWithRetry function in this commit https://github.com/MetaMask/web3-provider-engine/commit/caaf92bd472c8738d508181d7fd5445df8da432f

## Actual Results

Refer to actual results in the above "Steps to Reproduce" section
## Environment

* Operating System: macOS Mojave 10.14.6
* Ethereum client: Infura
* Truffle version (`truffle version`): N/A ("@truffle/hdwallet-provider": "^1.0.36")
* node version (`node --version`): v14.4.0
* npm version (`npm --version`): 6.14.5

### PR DESCRIPTION
**Pull request by ltfschoen**
Fixes https://github.com/trufflesuite/truffle/issues/3130 with changes to match those in https://github.com/MetaMask/web3-provider-engine/blob/master/index.js by @kumavis

### CODE REVIEW

**Review by CruzMolina — APPROVED** [review]
Sweeeet. Thanks @ltfschoen !

Just smoke-tested this a bunch and can confirm the relevant error goes away with these commits.

It would be nice to just pull in the commits up until the `web3-provider-engine` version this bug was resolved in, but it looks likes 15.x swapped out some subprovider implementations that are used in `@truffle/hdwallet-provider`.

**Comment by ltfschoen** [comment]
Ok, so it looks like this repo has all the same commits of MetaMask/web3-provider-engine's repo up until this 15.0.0 commit https://github.com/MetaMask/web3-provider-engine/commit/5f7acf6c96028f151b5d3ad2a99cb935056f2b71, and they resolved the invalid block error a couple of commits later in this commit on 24 April 2019 https://github.com/MetaMask/web3-provider-engine/commit/21b1849b5433c0df5371c13a33922c7e1ee83374, but that change was also merged in this later commit on 20 August 2019
https://github.com/MetaMask/web3-provider-engine/commit/8ee565e5acb33a424c42afd15c88639b06489f01, and then later it was improved in this commit https://github.com/MetaMask/web3-provider-engine/commit/fae46ddf3b5b768ffb3e871489d8d8c6d444e236 on 20 February 2020 where `_getBlockByNumberWithRetry` was added.
And this PR reflects all those changes.

**Comment by ltfschoen** [comment]
Is there anything in the repo that they mention here that could be useful too? https://github.com/MetaMask/web3-provider-engine/commit/921e9561abd60ee91bbd57c43669e955c2145710

**Comment by CruzMolina** [comment]
@ltfschoen I don't believe we've scoped out what necessary changes we'd have to make on our end to configure `hdwallet-provider` to use `json-rpc-engine` instead of `web3-provider-engine`.

Hopefully the changes made here suffice for now 🤞 .

**Pull request merged**
